version: "2.1"
services:
  opbeans-node:
    build: .
    image: opbeans/opbeans-node:latest
    ports:
      - "${OPBEANS_NODE_PORT:-8000}:3000"
    container_name: opbeans-node
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    environment:
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-node}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://3fea75f56bf14d4ca6fa99b7f5a6658c.apm.europe-west1.gcp.cloud.es.io}
      - ELASTIC_APM_SECRET_TOKEN=qYD4B8nyn8RIbhdQI4
      - ELASTIC_APM_APPLICATION_PACKAGES=co.elastic.apm.opbeans
      - ELASTIC_APM_JS_SERVER_URL=${ELASTIC_APM_JS_SERVER_URL:-https://3fea75f56bf14d4ca6fa99b7f5a6658c.apm.europe-west1.gcp.cloud.es.io}
      - ELASTIC_APM_JS_SERVICE_NAME=${ELASTIC_APM_JS_SERVICE_NAME:-opbeans-react}
      - NODE_ENV=production
      - OPBEANS_SERVER_PORT=${OPBEANS_SERVER_PORT:-3000}
      - PGHOST=lio-backend-1
      - PGUSER=postgres
      - PGPASSWORD=hunter2
      - PGDATABASE=opbeans
      - REDIS_URL=redis://lio-backend-1:6379
    depends_on:
      apm-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--server-response", "-O", "/dev/null", "http://opbeans-node:3000/"]
      interval: 10s
      retries: 10